ARG PYTHON_VERSION_TAG=3.13

FROM python:$PYTHON_VERSION_TAG-slim AS python-builder

ARG USE_CUDA=0

WORKDIR /home/user

ENV UV_LINK_MODE=copy
ENV UV_COMPILE_BYTECODE=1
ENV UV_LOCKED=1
ENV UV_NO_DEV=1
ENV UV_NO_CACHE=1
ENV UV_NO_EDITABLE=1
ENV PYTHONOPTIMIZE=2

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/
COPY pyproject.toml uv.lock ./

RUN uv sync --no-install-project ${USE_CUDA:+--extra cuda}

COPY . .

RUN uv sync ${USE_CUDA:+--extra cuda}


FROM python:$PYTHON_VERSION_TAG-slim

ARG PYTHON_VERSION_TAG
ARG USE_CUDA=0

ENV HOME=/home/user
ENV PATH=$HOME/.venv/bin:$PATH
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV TRANSFORMERS_NO_ADVISORY_WARNINGS=1
ENV USE_CUDA=$USE_CUDA
ENV LD_LIBRARY_PATH=$HOME/.venv/lib/python$PYTHON_VERSION_TAG/site-packages/nvidia/cublas/lib

RUN useradd -m -u 1000 user

USER user

WORKDIR $HOME

COPY --chown=user --from=python-builder $HOME/.venv .venv

CMD ["llm-api"]
