FROM python:slim AS model-builder

RUN pip install huggingface_hub
RUN python -c \
    "from huggingface_hub import snapshot_download; \
    snapshot_download('winstxnhdw/Llama-3.2-1B-Instruct-ct2-int8');"


FROM python:3.13-slim@sha256:ae9f9ac89467077ed1efefb6d9042132d28134ba201b2820227d46c9effd3174 AS python-builder

WORKDIR /home/user

ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy
ENV UV_NO_CACHE=1

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
COPY pyproject.toml uv.lock ./

RUN uv sync --frozen --no-dev --no-editable --no-install-project

COPY . .

RUN uv sync --frozen --no-dev --no-editable


FROM python:3.13-slim@sha256:ae9f9ac89467077ed1efefb6d9042132d28134ba201b2820227d46c9effd3174

ENV HOME=/home/user
ENV PATH=$HOME/.venv/bin:$PATH
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV HF_HUB_OFFLINE=1

RUN useradd -m -u 1000 user

USER user

WORKDIR $HOME

COPY --chown=user --from=model-builder  /root/.cache/huggingface $HOME/.cache/huggingface
COPY --chown=user --from=python-builder $HOME/.venv .venv

CMD ["llm-api"]
