FROM python:slim@sha256:f3614d98f38b0525d670f287b0474385952e28eb43016655dd003d0e28cf8652 AS model-builder

RUN pip install huggingface_hub
RUN python -c \
    "from huggingface_hub import snapshot_download; \
    snapshot_download('winstxnhdw/Llama-3.2-3B-Instruct-ct2-int8');"


FROM python:3.12-slim@sha256:aaa3f8cb64dd64e5f8cb6e58346bdcfa410a108324b0f28f1a7cc5964355b211 AS python-builder

WORKDIR /home/user

ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy
ENV UV_NO_CACHE=1

COPY --from=ghcr.io/astral-sh/uv:latest@sha256:562193a4a9d398f8aedddcb223e583da394ee735de36b5815f8f1d22cb49be15 /uv /uvx /bin/
COPY pyproject.toml uv.lock ./

RUN uv sync --frozen --no-dev --no-editable --no-install-project

COPY . .

RUN uv sync --frozen --no-dev --no-editable


FROM python:3.12-slim@sha256:aaa3f8cb64dd64e5f8cb6e58346bdcfa410a108324b0f28f1a7cc5964355b211

ENV HOME=/home/user
ENV PATH=$HOME/.venv/bin:$PATH
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV HF_HUB_OFFLINE=1

RUN useradd -m -u 1000 user

USER user

WORKDIR $HOME

COPY --chown=user --from=model-builder  /root/.cache/huggingface $HOME/.cache/huggingface
COPY --chown=user --from=python-builder $HOME/.venv .venv

CMD ["llm-api"]
